### PR TITLE
Update quick-start-guide.markdown

### PR DESCRIPTION
**Pull request by stargater**
Edit:
- installation description

Add:
- installation for tntdb

### CODE REVIEW

**Comment by maekitalo** [comment]
The quick start guide handles tntnet. And tntnet do not depend on tntdb. Therefore the installation of tntdb is not part of the installation of tntnet and hence should not be part of the quick start guide.

A separate section how to add other libraries and use tntdb as a example would be good to have. But currently I plan to rewrite the quick start guide completely. The new tool tntnet-project covers much more than the previous simple project generated with tntnet-config. And so should the quick start guide cover the basics of the generated project.

**Comment by jplatte** [comment]
There are two complete guides, the one that is on the website and [the one that I wrote](https://gist.github.com/jplatte/9974777) some time ago. Why completely rewrite it once again?

**Comment by maekitalo** [comment]
Sorry but I don't think, that your guide can replace the quick start guide. There are quite something to discuss.

I have also worked on tntnet-project and I would like to write a guide, which concentrates on the things I've done there.

**Comment by jplatte** [comment]
IIRC the last time I mentioned it the only thing you wanted to discuss was whether tntnet-config should also be in the tutorial, but I'll write you a mail about that later. Of course I'm okay with having a more comprehensible guide with more content than just how to use ECPP, but I'd really like to see my work integrated in the next guide.

**Pull request closed without merging**
